config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"

    get "/about-us", to: "static_pages#about_us"
    get "/contact-us", to: "static_pages#contact_us"
    get "/car-list", to: "posts#index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout",  to: "sessions#destroy"
    post "favorite_lists/update"
    post "posts/update_index"

    resources :favorite_lists, only: %i(show update index)
    resources :posts
    resources :users, only: %i(show new create)
    resources :posts do
      resources :comments, only: %i(new create destroy)
    end
    resources :comments, only: %i(new create destroy) do
      resources :comments, only: %i(new create destroy)
    end

    namespace :admins do
      root "posts#index"
      post "posts/change_activated"
      resources :posts
    end
  end
end

app/views/admins/layouts/_navbar.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <a class="navbar-brand" href="index.html"><%= t "admin_side" %></a>
  <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
  <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
    <div class="input-group">
    </div>
  </form>
  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <%= link_to t("log_out"), logout_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>
  </ul>
</nav>

app/views/admins/layouts/_sidebar.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            <%= t "admins.manage" %>
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
          </a>
          <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav">
              <%= link_to t("admins.manage_posts"), admins_posts_path, class: "nav-link" %>
            </nav>
          </div>
        </div>
      </div>
    </nav>
  </div>