config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"

    get "/about-us", to: "static_pages#about_us"
    get "/contact-us", to: "static_pages#contact_us"
    get "/car-list", to: "posts#index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout",  to: "sessions#destroy"
    post "favorite_lists/update"
    post "posts/update_index"

    resources :favorite_lists, only: %i(show update index)
    resources :posts
    resources :users, only: %i(show new create)
    resources :posts do
      resources :comments, only: %i(new create destroy)
    end
    resources :comments, only: %i(new create destroy) do
      resources :comments, only: %i(new create destroy)
    end

    namespace :admins do
      root "posts#index"
      post "posts/change_activated"
      resources :posts
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  POST_PARAMS = [:name, :content, :activated, car_attributes:
    [:year_of_manufacture_id, :origin_id, :gearbox_id, :car_type_id, :brand_id,
      :car_model_id, :color_id, :number_of_seat_id, :condition_id, :fuel_id,
        :image, :price, :mileage]].freeze

  belongs_to :user
  has_one :car, dependent: :destroy
  has_many :favorite_lists, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  accepts_nested_attributes_for :car, allow_destroy: true, update_only: true

  validates :name, presence: true, length: {maximum: Settings.post.name_length}
  validates :content, presence: true, length:
    {maximum: Settings.post.content_length}
  validates_associated :car

  scope :by_user_id, ->(user_id){where user_id: user_id}

  scope :by_post_id, ->(post_id){where post_id: post_id}

  scope :by_ids, ->(ids){where id: ids}

  scope :by_year_of_manufacture, (lambda do |year_of_manufacture_ids|
    if year_of_manufacture_ids.present?
      where cars: {year_of_manufacture_id: year_of_manufacture_ids}
    end
  end)

  scope :by_origin, (lambda do |origin_ids|
    where cars: {origin_id: origin_ids} if origin_ids.present?
  end)

  scope :by_gearbox, (lambda do |gearbox_ids|
    where cars: {gearbox_id: gearbox_ids} if gearbox_ids.present?
  end)

  scope :by_car_type, (lambda do |car_type_ids|
    where cars: {car_type_id: car_type_ids} if car_type_ids.present?
  end)

  scope :by_brand, (lambda do |brand_ids|
    where cars: {brand_id: brand_ids} if brand_ids.present?
  end)

  scope :by_car_model, (lambda do |car_model_ids|
    where cars: {car_model_id: car_model_ids} if car_model_ids.present?
  end)

  scope :by_color, (lambda do |color_ids|
    where cars: {color_id: color_ids} if color_ids.present?
  end)

  scope :by_number_of_seat, (lambda do |number_of_seat_ids|
    if number_of_seat_ids.present?
      where cars: {number_of_seat_id: number_of_seat_ids}
    end
  end)

  scope :by_condition, (lambda do |condition_ids|
    where cars: {condition_id: color_ids} if condition_ids.present?
  end)

  scope :by_fuel, (lambda do |fuel_ids|
    where cars: {fuel_id: fuel_ids} if fuel_ids.present?
  end)

  scope :include_car, ->{includes :car}

  scope :by_created_at, ->{order created_at: :desc}

  scope :by_updated_at, ->{order updated_at: :desc}

  scope :by_activated, ->{where activated: true}

  scope :by_favorite_count, (lambda do
    left_joins(:favorite_lists).group(:id).order("COUNT(posts.id) DESC")
  end)

  scope :this_month, (lambda do
    where "MONTH(favorite_lists.created_at) = ?", Time.zone.now.strftime("%m")
  end)

  scope :order_by_higher_price, (lambda do
    left_joins(:car).order("cars.price DESC")
  end)

  scope :order_by_lower_price, (lambda do
    left_joins(:car).order("cars.price ASC")
  end)

  delegate :name, to: :user, prefix: true
  delegate :price, :image, :year_of_manufacture_name, :gearbox_name,
           :origin_name, :car_type_name, :brand_name, :car_model_name,
           :color_name, :number_of_seat_name, :condition_name, :fuel_name,
           :mileage, to: :car, prefix: true
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < AdminsController
  before_action :logged_in_user, only: %i(new create destroy)
  before_action :load_posts, only: :index
  before_action :load_post, only: %i(update edit destroy change_activated)

  def index
    @posts = load_posts.by_created_at.page(params[:page]).per Settings.page_ad
  end

  def show; end

  def new
    @post = Post.new
    @post.build_car
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      flash[:success] = t ".create_success"
      redirect_to admins_posts_path
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def edit; end

  def update
    if @post.update post_params
      flash[:success] = t ".update_success"
      redirect_to admins_posts_path
    else
      flash[:danger] = t ".update_fail"
      render "admins/posts/edit"
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_to admins_root_path
  end

  def change_activated
    @post.activated = !@post.activated
    @post.save
    respond_to :js
  end

  private

  def post_params
    params.require(:post).permit Post::POST_PARAMS
  end

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post

    flash[:danger] = t "posts.not_found_post"
    redirect_to admins_root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: %i(new create destroy)
  before_action :load_posts, only: :index
  before_action :load_post, only: %i(show update edit)
  before_action :correct_user, only: %i(update edit destroy)
  before_action :check_activated?, only: :show

  def index
    @posts = load_posts.by_activated.by_updated_at
    .page(params[:page]).per Settings.page
  end

  def show
    @favorite_list_exists = FavoriteList.by_user_id(current_user)
    .by_post_id(@post.id).present?
    @favorite_count = FavoriteList.by_post_id(@post.id).size
  end

  def new
    @post = Post.new
    @post.build_car
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      flash[:success] = t ".create_success"
      redirect_to @post
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def edit; end

  def update
    if @post.update post_params
      flash[:success] = t ".update_success"
      redirect_to @post
    else
      flash[:danger] = t ".update_fail"
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_back_or @post.user
  end

  def update_index
    @posts = params[:sort_id].to_i == 1 ? load_posts.order_by_lower_price : load_posts.order_by_higher_price
    @posts = @posts.by_activated.page(params[:page]).per Settings.page
    respond_to :js
  end

  private

  def post_params
    params.require(:post).permit Post::POST_PARAMS
  end

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post

    flash[:danger] = t "posts.not_found_post"
    redirect_to car_list_path
  end

  def correct_user
    @post = current_user.posts.find_by id: params[:id]
    return if @post

    flash[:danger] = t "posts.not_found_post"
    redirect_to car_list_path
  end

  def check_activated?
    @post = Post.by_activated.find_by(id: params[:id]) ||
      current_user.posts.find_by(id: params[:id])
    return if @post

    flash[:danger] = t "posts.not_found_post"
    redirect_to car_list_path
  end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
  def post_activated_text activated
    activated ? t("admins.active") : "admins.inactive"
  end
end

app/helpers/posts/posts_helper.rb
module Posts::PostsHelper
  def load_dropdown model
    model.pluck :name, :id
  end

  def number_to_price price
    if price < Settings.second_price_limit
      price.to_s + Settings.second_price
    elsif price.to_s.last(Settings.second_price_count).sub(/^0+/, "").blank?
      (price / Settings.second_price_limit).to_s + Settings.first_price
    else
      (price / Settings.second_price_limit).to_s + Settings.first_price +
        price.to_s.last(Settings.second_price_count).sub(/^0+/, "") +
        Settings.second_price
    end
  end

  def status_text status
    status ? t("admins.active") : t("admins.inactive")
  end
end

app/views/admins/posts/_form.html.erb
<%= form_for [:admins, @post] do |f| %>
  <%= render "shared/error_messages", object: @post %>
  <%= f.label :name, t("posts.new.name") %>
  <%= f.text_field :name, class: "form-control", required: true %>
  <%= f.label :content, t("posts.new.content") %>
  <%= f.text_area :content, class: "form-control", required: true %>
  <%= render "/posts/car_form", f: f %>
  <%= f.label :activated, t("posts.new.status") %>
  <%= f.select(:activated, [[t("admins.active"), true], [t("admins.inactive"), false]], {}, class: "form-control" )%>
  <div class="courses-info">
    <%= f.submit yield(:button_text), class: "section-btn btn
      btn-primary btn-block" %>
  </div>
<% end %>

app/views/admins/posts/_post.html.erb
<tr>
  <td><%= post.name %></td>
  <td><%= image_tag post.car_image.url, size: Settings.image_size_admin, class: "img-responsive"  %></td>
  <td><%= post.car_year_of_manufacture_name %></td>
  <td><%= post.car_car_type_name %></td>
  <td><%= post.created_at.strftime Settings.date_time_format %></td>
  <td><%= number_to_price post.car_price %></td>
  <td>
    <%= button_tag id:"btn-activated-#{post.id}", class: "btn btn-primary btn-activated", post_id: "#{post.id}" do %>
      <%= post_activated_text post.activated %>
    <% end %>
  </td>
  <td>
    <%= link_to edit_admins_post_path(post.id), class: "section-btn btn btn-primary btn-block" do %>
      <i class="fas fa-edit"></i> <%= t("edit") %>
    <% end %>
    <%= link_to admins_post_path(post.id), method: :delete, data: { confirm: t("admins.you_sure") }, class: "section-btn btn btn-primary btn-block" do %>
      <i class="fas fa-trash-alt"></i> <%= t "delete" %>
    <% end %>
  </td>
</tr>

app/views/admins/posts/change_activated.js.erb
$('#btn-activated-<%= @post.id %>').html('<%= post_activated_text @post.activated %>');

app/views/admins/posts/edit.html.erb
<% provide :title, t("edit_post") %>
<% provide :button_text, t("posts.new.save_changes") %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid">
      <h1 class="mt-4"><%= yield(:title) %></h1>
      <div class="card mb-4">
      </div>
      <div class="card mb-4">
        <div class="card-body-form">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/admins/posts/index.html.erb
<% provide :title, t("admins.manage_posts") %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid">
      <h1 class="mt-4 mb-4"><%= yield(:title) %></h1>
      <div class="col-md-3 mb-4">
        <%= link_to new_admins_post_path, class: "section-btn btn btn-primary btn-block" do %>
          <i class="fa fa-plus-circle"></i> <%= t("posts.new.create_post") %>
        <% end %>
      </div>
      <div class="card mb-4">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th><%= t("posts.new.name") %></th>
                  <th><%= t("posts.new.image") %></th>
                  <th><%= t("posts.new.year_of_manufacture") %></th>
                  <th><%= t("posts.new.car_type") %></th>
                  <th><%= t("created_at") %></th>
                  <th><%= t("posts.new.price") %></th>
                  <th><%= t("posts.new.status") %></th>
                  <th colspan="2"></th>
                </tr>
              </thead>
              <tbody>
                <%= render @posts %>
                <%= paginate @posts %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/admins/posts/new.html.erb
<% provide :title, t(".create_post") %>
<% provide :button_text, t("posts.new.create") %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid">
      <h1 class="mt-4"><%= yield(:title) %></h1>
      <div class="card mb-4">
      </div>
      <div class="card mb-4">
        <div class="card-body-form">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </main>
</div>