config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"

    get "/about-us", to: "static_pages#about_us"
    get "/contact-us", to: "static_pages#contact_us"
    get "/car-list", to: "posts#index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout",  to: "sessions#destroy"
    post "favorite_lists/update"
    post "posts/update_index"

    resources :favorite_lists, only: %i(show update index)
    resources :posts
    resources :users, only: %i(show new create)
    resources :posts do
      resources :comments, only: %i(new create destroy)
    end
    resources :comments, only: %i(new create destroy) do
      resources :comments, only: %i(new create destroy)
    end

    namespace :admins do
      root "posts#index"
      post "posts/change_activated"
      resources :posts
    end
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6">
        <div class="footer-info">
          <div class="section-title">
            <h2><%= t ".headquarter" %></h2>
          </div>
          <address>
            <p>212 Barrington Court <br>
              New York, ABC 10001</p>
          </address>
          <ul class="social-icon">
            <li><a href="#" class="fa fa-facebook-square" attr="facebook icon"></a></li>
            <li><a href="#" class="fa fa-twitter"></a></li>
            <li><a href="#" class="fa fa-instagram"></a></li>
          </ul>
          <div class="copyright-text">
            <p><%= t ".copy_right" %> &copy; <%= t ".company_name" %></p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6">
        <div class="footer-info">
          <div class="section-title">
            <h2><%= t ".contact_info" %></h2>
          </div>
          <address>
            <p>+1 333 4040 5566</p>
            <p><a href="mailto:contact@company.com">contact@company.com</a></p>
          </address>
          <div class="footer_menu">
            <h2><%= t ".quick_links" %></h2>
            <ul>
              <li><%= link_to t("home"), root_path %></li>
              <li><%= link_to t("car_list"), car_list_path %></li>
              <li><%= link_to t("news"), "#" %></li>
              <li><%= link_to t("about_us"), about_us_path %></li>
              <li><%= link_to t("contact_us"), contact_us_path %></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="footer-info newsletter-form">
          <div class="section-title">
            <h2><%= t ".newsletter_signup" %></h2>
          </div>
          <div>
            <div class="form-group">
              <form action="#" method="get">
                <input type="email" class="form-control" placeholder="<%= t ".enter_your_email" %>" name="email" id="email" required>
                <input type="submit" class="form-control" name="submit" id="form-submit" value="<%= t ".send_me" %>">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<section class="navbar custom-navbar navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon icon-bar"></span>
        <span class="icon icon-bar"></span>
        <span class="icon icon-bar"></span>
      </button>
      <%= link_to t("car_shop"), root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-nav-first">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t(".car_list"), car_list_path %></li>
        <li><%= link_to t("news"), "#" %></li>
        <li><%= link_to t("about_us"), about_us_path %></li>
        <li><%= link_to t("contact_us"), contact_us_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to current_user.name, user_path(current_user.id),
            class: "dropdown-toggle", "data-toggle": "dropdown" %>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li class="divider"></li>
              <li><%= link_to t("favorite_list"), favorite_lists_path %></li>
              <li class="divider"></li>
              <li><%= link_to t("log_out"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("log_in"), login_path %></li>
        <% end %>
        <li class="dropdown">
          <%= link_to t("language"), "#", class: "dropdown-toggle", "data-toggle": "dropdown" %>
          <ul class="dropdown-menu">
            <li><%= link_to t(".en"), locale: :en %></li>
            <li class="divider"></li>
            <li><%= link_to t(".vi"), locale: :vi %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</section>

app/views/layouts/_rails_admin_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "admins/admins", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "admins", "data-turbolinks-track": "reload" %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "admins/admins", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "admins", "data-turbolinks-track": "reload" %>
  </head>
  <body class="sb-nav-fixed">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <%= render "admins/layouts/navbar" %>
    <%= render "admins/layouts/sidebar" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= render "layouts/rails_default" %>
  </head>
  <body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>

</html>